// Resolve showtime's Node dependencies from ~/.showtime/node.
//
// ESM ignores NODE_PATH, so scripts cannot `import 'playwright'` directly.
// Use:
//   import { importDep, requireDep, depPath } from './lib/deps.mjs';
//   const { chromium } = await importDep('playwright');   // ESM or CJS packages
//   const d3 = await importDep('d3');
//   const katexCss = depPath('katex', 'dist', 'katex.min.css'); // file path for serving /_lib/...
//
// importDep() resolves bare specifiers exactly as Node would from inside
// ~/.showtime/node (full ESM "exports" conditions), via a tiny loader module
// kept in that folder. requireDep() is the CommonJS flavour (createRequire).
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));

/** Runtime home: $SHOWTIME_HOME or ~/.showtime */
export function showtimeHome() {
  return process.env.SHOWTIME_HOME || path.join(os.homedir(), '.showtime');
}

/** The skill directory (…/skills/showtime). */
export function skillDir() {
  return process.env.SHOWTIME_SKILL || path.resolve(HERE, '..', '..');
}

/** ~/.showtime/node (package.json lives here). */
export function nodeDir() {
  if (process.env.SHOWTIME_NODE_MODULES) return path.dirname(process.env.SHOWTIME_NODE_MODULES);
  return path.join(showtimeHome(), 'node');
}

/** ~/.showtime/node/node_modules */
export function nodeModulesDir() {
  return process.env.SHOWTIME_NODE_MODULES || path.join(nodeDir(), 'node_modules');
}

function missing(name, err) {
  const e = new Error(
    `showtime: Node package "${name}" is not installed in ${nodeModulesDir()}.\n` +
    `  run: showtime setup   (then: showtime doctor)` + (err ? `\n  cause: ${err.message}` : ''));
  e.code = 'SHOWTIME_DEP_MISSING';
  return e;
}

let _require;
function req() {
  if (!_require) _require = createRequire(path.join(nodeDir(), 'package.json'));
  return _require;
}

/** CommonJS require() of a dependency installed in ~/.showtime/node. */
export function requireDep(name) {
  try {
    return req()(name);
  } catch (err) {
    if (err && (err.code === 'MODULE_NOT_FOUND' || err.code === 'ERR_MODULE_NOT_FOUND')) throw missing(name, err);
    throw err;
  }
}

/** Absolute path a CommonJS resolution of `spec` would load. */
export function resolveDep(spec) {
  try {
    return req().resolve(spec);
  } catch (err) {
    throw missing(spec, err);
  }
}

/** Path inside an installed package, e.g. depPath('katex', 'dist', 'katex.min.css'). */
export function depPath(pkg, ...rel) {
  return path.join(nodeModulesDir(), ...pkg.split('/'), ...rel);
}

/** Installed version of a package, or null. */
export function depVersion(pkg) {
  try {
    return JSON.parse(fs.readFileSync(depPath(pkg, 'package.json'), 'utf8')).version || null;
  } catch {
    return null;
  }
}

const LOADER = '// generated by showtime: resolves bare specifiers from this folder\n' +
  'export default (spec) => import(spec);\n';

let _loader;
async function loader() {
  if (_loader) return _loader;
  const file = path.join(nodeDir(), 'showtime-import.mjs');
  let current = null;
  try { current = fs.readFileSync(file, 'utf8'); } catch { /* missing */ }
  if (current !== LOADER) {
    if (!fs.existsSync(nodeModulesDir())) throw missing('(all packages)');
    fs.writeFileSync(file, LOADER);
  }
  _loader = (await import(pathToFileURL(file).href)).default;
  return _loader;
}

/** Dynamic import() of a dependency (ESM-only packages work too). */
export async function importDep(spec) {
  const load = await loader();
  try {
    return await load(spec);
  } catch (err) {
    if (err && (err.code === 'ERR_MODULE_NOT_FOUND' || err.code === 'MODULE_NOT_FOUND')) throw missing(spec, err);
    throw err;
  }
}
